module.exports = {
    USERS_COLLECTION: 'users',
    ADMIN_COLLECTION: 'admin',
    CART_COLLECTION: 'cart',
    ORDER_COLLECTION: 'order',
    STAFF_COLLECTION: "staffs",
    FEEDBACK_COLLECTION: "feedback",
    NOTIFICATIONS_COLLECTION: "notification",
    ROOM_COLLECTION: "rooms",
    CATEGORY_COLLECTION: "category",
    ASSIGNED_ROOMS: "assigned-rooms",
    ASSIGN_STAFF: "assigned-staffs",
    DISCOUNTS_COLLECTION: "discounts",
    SETTINGS_COLLECTION: "settings",
}